/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: berzerk (https://sketchfab.com/makameko300)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/batman-aa79a79de2b943aeb78dd8e11764d4ea
Title: Batman
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Batman(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/batman.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    if(animations.length>0){
        actions[animations[0].name]?.play()
    }
  },[actions,animations])
  return (
    <group ref={group} {...props} dispose={null}
     rotation={[-Math.PI / 2, -0.2, 2.2]} 
    scale={props.scale || 0.3}
    position={props.position || [1.5,3,-1]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={90.402}>
          <group name="Batmanfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.H_BatMan_D}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/batman.glb')
